### ISSUE TITLE
Is it possible to use Promises instead of callbacks?

### ISSUE THREAD

**Issue by jhyland87** [cpsubrian/node-stact-hooks#1]
Im looking at using this repository for a project I'm working on, which uses the BluebirdJS Promise library, and I was wondering if theres a way to have node-stact-hooks return promises instead of callbacks? 

I thought it would be as easy as using something like the [promisifyall](http://bluebirdjs.com/docs/api/promise.promisifyall.html) method, but I cant seem to get it to work.

Thanks!

**Comment by cpsubrian** [comment]
I'd have to actually try to use promises to confirm as such, but my guess is that `stact`, which does the heavy lifting here, isn't particularly compatible with promises and promisification. It deals with dynamic lengths of arguments and callback detection in a way that I would suspect makes it hard for bluebird to deal with. For example stuff like this (which was a critical performance optimization):

https://github.com/cpsubrian/node-stact/blob/master/stact.js#L131-L150

If you had some sample code I could look at maybe I could come up with ideas.

**Comment by jhyland87** [comment]
Theres a few things I've tried, some _kinda_ work, and some dont

### Attempt #1

I tried using the `filter` on Bluebirds [PromisifyAll](http://bluebirdjs.com/docs/api/promise.promisifyall.html) (which, to be honest/fair, I've never had good luck using `PromisifyAll`):

``` javascript
var hooks  = Promise.promisifyAll(require('stact-hooks')(), {
    filter: function(name, func, target, passesDefaultFilter) {
        return name === 'run'
    }
})
```

This attempt doesn't execute any of the hooks.. but it also doesn't throw an error. I tried putting some `console.log` functions in the `filter`, and they weren't displayed, so I'm sure I'm doing that incorrectly

### Attempt #2

Next, I used the [promisify](http://bluebirdjs.com/docs/api/promise.promisify.html) method on hooks `run` method, where I was specifying the hook manually:

``` javascript
var hookRunBeforeSave = Promise.promisify( hooks( 'before:save' ).run )
var hookRunAfterSave = Promise.promisify( hooks( 'after:save' ).run )

console.log('About to execute before:save')

hookRunBeforeSave()
    .then( results => {
        console.log('before:save executed successfully')

        console.log('About to execute after:save')
        return hookRunAfterSave()
    })
    .then( results => {
        console.log('after:save executed successfully')
    })
    .catch( err => {
        console.log('ERROR:',err)
    })
```

This actually worked, but hardcoding the hooks is just ridiculous, so I tried to change that next..

### Attempt #3

I tried to basically use the same thing as the previous attempt, but tried to change how the hook name was specified when the `run` method is called:

``` javascript
var hooks = require('stact-hooks')()
var hooks_run = Promise.promisify( hook_name => hooks( hook_name ).run() )

console.log('About to execute before:save')

hooks_run('before:save')
    .then( results => {
        console.log('before:save executed successfully')

        console.log('About to execute after:save')
        return hooks_run('after:save')
    })
    .then( results => {
        console.log('after:save executed successfully')
    })
    .catch( err => {
        console.log('ERROR:',err)
    })
```

But this wouldnt work at all. The `console.log` output wasn't shown (Except for the first one thats not in a promise/hook), but there also wasn't any error messages.

Well, thats all ive got so far. Thanks for looking!

**Comment by jhyland87** [comment]
Update..

### Attempt #4

I  messed around with the idea in **Attempt #3** above, and it works:

``` javascript
var promises = {}
var hooks_run = function( hook_name ){
  if( typeof promises[ hook_name ] === 'undefined' ){
    promises[ hook_name ] = Promise.promisify( hooks( hook_name ).run )
  }

  return promises[ hook_name ]
}

console.log('About to execute before:save')

hooks_run('before:save')()
  .then( results => {
    console.log('before:save executed successfully')

    console.log('About to execute after:save')
    return hooks_run('after:save')()
  })
  .then( results => {
    console.log('after:save executed successfully')
  })
  .catch( err => {
    console.log('ERROR:',err)
  })
```

Not sure this is the best way to go about doing it though. Managing the promises in an external object is just... messy. But if theres no other way, then ill do it.

**Comment by cpsubrian** [comment]
Well, what you're basically doing in #4 is rewriting this whole module. Which is perfectly fine :) Note that **this** is the entirety of this module:

``` js
var createStact = require('stact');

function createHooks (options) {
  var stacks = {};

  return function getStact (name) {
    if (!stacks[name]) {
      stacks[name] = createStact(options);
    }
    return stacks[name];
  };
}

module.exports = createHooks;
```

So, you could make a promise-based version (and publish it to npm, if you like) something like:

``` js
var createStact = require('stact');

function createHooks (options) {
  var stacks = {};

  return function getStact (name) {
    if (!stacks[name]) {
      stacks[name] = createStact(options);
      stacks[name].run = Promise.promisify(stacks[name].run, {context: stacks[name]});
      stacks[name].runSeries = Promise.promisify(stacks[name].runSeries, {context: stacks[name]});      
      stacks[name].runWaterfall = Promise.promisify(stacks[name].runWaterfall, {context: stacks[name]});      
    }
    return stacks[name];
  };
}

module.exports = createHooks;
```

**Comment by cpsubrian** [comment]
One thing that surprises me though, is that you'd only want to promisify the hook registry (this module). `Stact` is what actually manages and calls all the functions you register and as far as I can recall it doesn't support promises. So what you may really want is a version of `stact` that has better promise integration also.

`Stac`, which is what `Stact` is built on, however would have no problem with promises since it just stores and returns sorted arrays of things.

**Comment by jhyland87** [comment]
Hm, ok, thanks for the input! Ill check it out.

**Comment by jhyland87** [comment]
Btw, you said you were surprised I wanted to use promises instead of callbacks. Im actually writing something that others can create plugins for, which is what this is for. And I find that some people like callbacks... some like promises. I personally like promises.

To find a middle ground, I use BluebirdJS's [asCallback](http://bluebirdjs.com/docs/api/ascallback.html) method, and some nifty Lodash functions to allow callbacks AND/OR promises... like so:

``` javascript
/**
 * Get the function farthest to the right in the arguments provided. If the `drop` argument is
 * defined (as a number), then ignore that number of arguments (from the left) while looking
 * for a defined function (basically, the number of non-callback args)
 *
 * @param   {array}     args    The `arguments` from the executing function
 * @param   {number=}   drop    Number of items to drop from the args array 
 * @returns {function=}         Returns the function found, or undefined
 */
var _getCb = function( args, drop ){
    if( _.isNumber( drop ) ){
        args = _.drop( args, drop )
    }

    return _.chain( args ).findLast( a => _.isFunction( a ) ).value()
}

// Example of how to only allow a callback in the last two arguments
var getFullName = ( first, last, middleOrCb, cb ) => {
    return new Promise( ( res, rej ) => {

        // Do cool stuff

    } ).asCallback( _getCb( arguments, 2 ) )
    // Obviously, if any of the arguments could be a callback, then just use `arguments` in  asCallback()
}

// As callbacks...
getFullName( 'John','Doe', ( err, data ) => { 
    if( err ) // handle error

    // Handle data
} )
getFullName( 'Jane','Doe', 'Smith', ( err, data ) => { 
    if( err ) // handle error

    // Handle data
} )

// As promises..
getFullName( 'John','Doe' )
    .then( data => /* Handle Data */ )
    .catch( err => /* Handle Error */ )

getFullName( 'Jane','Doe', 'Smith')
    .then( data => /* Handle Data */ )
    .catch( err => /* Handle Error */ )
```

I may fork your project and use that, unless you want to do it. Or I can do a pull request on yours, implement this, then you can merge it if you want.

This would allow you to keep backwards compatibility while allow promises. Users would just need to install BluebirdJS as a dependency. Lmk what you think!

**Comment by jhyland87** [comment]
### Edit

Im actually looking through the code now, it looks like I would actually need to mess with the [run](https://github.com/cpsubrian/node-stact/blob/master/stact.js#L31-L58) method of the `node-stact` repo.. As thats what has the `run` method.. So I might go ahead and do that.

But, since I interact with it through your repo, I may just fork node-stact, add the `asCallback` method, as well as the functionality from your repository...

If thats what happens, ill still give ya credit ;-) 

Thanks!

**Comment by cpsubrian** [comment]
> Btw, you said you were surprised I wanted to use promises instead of callbacks

Hehe, a slight miscommunication. I was talking about the fact that I'd assume you'd want the whole hook system to be promise-based ... aka the hooks themselves as well as the `run` function.

Instead of forking, you may be able to create a module that depends on, and extends, `stact`. Since `stact` exports the 'class', you can add to or override the prototype as needed. Alternatively, if you created a PR that adds optional promise support to any of these libs I'd happy review it.

I'd ideally want no performance regressions for the callback-based mode.

**Comment by cpsubrian** [comment]
Also, please feel free to fork, clone, copy, improve as needed. That's what open-source is about :) Certainly appreciate credit/link-backs if you do.

**Comment by jhyland87** [comment]
> Instead of forking, you may be able to create a module that depends on, and extends, stact. Since stact exports the 'class', you can add to or override the prototype as needed. Alternatively, if you created a PR that adds optional promise support to any of these libs I'd happy review it.

Yeah, thats what I was thinking about doing as well, and probably the route ill end up taking.

Thanks for the input!
